### ISSUE TITLE
"number-detail" method

### ISSUE THREAD

**Issue by krist1k** [kovinevmv/getcontact#1]
Great and clear code, but the method "number-detail" doesn't work in your API.Additional information about the person is not returned.

**Comment by kovinevmv** [comment]
Thanks.
Often additional information about phone number is not provided. To get it, user with this number must install original app GetContact and update phone status. After that everyone can get number-detail information. Please, test it on example phone number or use Premium Account with extra rights.

**Comment by kovinevmv** [comment]
Sometimes, when you send often requests to server, it doesn't returns any data and send captcha image. Try to send request again after few seconds
