### ISSUE TITLE
user not found

### ISSUE THREAD

**Issue by qran253** [kovinevmv/getcontact#11]
Hi,

after editing dump/tokens.yaml with my premium account cred-s, then while running python script 

python3 ./src/main.py -p +993555555555

Phone: +993555555555
User: Not Found

but with default script cred-s it works, i change only token,aes,priv keys

**Comment by kovinevmv** [comment]
Are you sure the number is in the correct format? On my free account does not find anything on this number.

I don’t have a premium account, so I can’t debug it. Perhaps API for the premium has a different format, and when authorization data for the premium account is sent as usual, the number is not found.

**Comment by qran253** [comment]
the number wrote here is example

**Comment by kovinevmv** [comment]
I tried to type your phone in app. It's not valid

![Screenshot from 2020-05-07 14-55-37](https://user-images.githubusercontent.com/21666349/81291676-ea4fef00-9072-11ea-84fd-77e6a14ebdbf.png)

**Comment by qran253** [comment]
> I tried to type your phone in app. It's not valid
> 
> ![Screenshot from 2020-05-07 14-55-37](https://user-images.githubusercontent.com/21666349/81291676-ea4fef00-9072-11ea-84fd-77e6a14ebdbf.png)

the number is example

**Comment by kovinevmv** [comment]
Please provide a screenshot or other information. I cannot debug work if you just say again that the same number does not work.

**Comment by dementiev27** [comment]
Hi, kovinevmv!
Sorry for asking, but is there's a need to use my own tokens (I don't have root and unable to get them), or your script can work with your public tokens?
Thanks for your time :)

**Comment by kovinevmv** [comment]
You can install the GenyMotion. There is a choice of emulated Android Version SDK. Each version supports root rights, so there will be no problems with access to the desired directory.
Also there are several sample tokens, but often they are dead

**Comment by dementiev27** [comment]
> @dementiev27, you can install the GenyMotion. There is a choice of emulated Android Version SDK. Each version supports root rights, so there will be no problems with access to the desired directory.
> Also there are several sample tokens, but often they are dead

Thanks for that, I'll definitely try it.
If you have some alive tokens, could you provide one more, please?

**Comment by kovinevmv** [comment]
All tokens that I have in the repository

**Comment by dementiev27** [comment]
@kovinevmv thanks very much!
I've got my own token and it's ok now, but the is one problem.
The script shows only the contact's name, but there are no tags.
How can I fix it?

**Comment by dementiev27** [comment]
Sorry again, I've tried again, it shows tags, but not for all contacts.
Good job, kovinevmv!

**Comment by kovinevmv** [comment]
Not all phones in Getcontact database. Check phone number in example. If script return the same output, token is valid.
