### ISSUE TITLE
Docker image stop building on tzdata interactive

### ISSUE THREAD

**Issue by dsultanr** [kovinevmv/getcontact#12]
Building docker container hangs on tzdata asking which region to setup

Dockerfile should be fixed:

RUN export DEBIAN_FRONTEND=noninteractive
RUN ln -fs /usr/share/zoneinfo/Europe/Moscow /etc/localtime
RUN apt-get install -y tzdata
RUN dpkg-reconfigure --frontend noninteractive tzdata

these lines should be added before 

RUN apt-get -y install tesseract-ocr

**Comment by kovinevmv** [comment]
Thanks.
[Updated](https://github.com/kovinevmv/getcontact/commit/af964217b5c337f3ad86ef21eb3fbd86f197e754)
