### ISSUE TITLE
token and aes key

### ISSUE THREAD

**Issue by merlanspace** [kovinevmv/getcontact#15]
Ку, не могу найти AES KEY, в файле, нашел только токен обычный, а приват ключ обез?

**Comment by kovinevmv** [comment]
Final key (aes) обязателен. Он там есть, проверил на последней версии (11/07/2020). 

![final key](https://downloader.disk.yandex.ru/preview/65b47f13830d63be0b25fe1f83fcba12ee0c2889a4eaad9f3de3677c36eedb5a/5f09f430/7gVk8bSldEHkx6I0cj9qQb89Mnqgrtods0aInVEl1i3a_nx-t8wJ2UbztI4ab_p1Y5eYEs3WPp7RXAdtIOZeSw==?uid=0&filename=Screenshot+from+2020-07-11+16-15-08.png&disposition=inline&hash=&limit=0&content_type=image%2Fpng&tknv=v2&owner_uid=213345701&size=2048x2048)
