### ISSUE TITLE
"Not found"

### ISSUE THREAD

**Issue by Matrix3007** [kovinevmv/getcontact#17]
Программа выводит "Not found" на любые входные данные, даже если номер есть в гетконтакте.

**Comment by kovinevmv** [comment]
Проверьте валидность токена. Скорее всего те токены, которые идут в качестве примера в репозитории, умерли.

**Comment by Matrix3007** [comment]
Там было 4 профиля. Я заменил данные в одном из них (в первом) на свои. Токен тоже заменил.

**Comment by kovinevmv** [comment]
Удалите все остальные, оставьте только один свой. Проверьте, что вы правильно введи токен, ключ aes, private key и остальные поля. Если не работает, то проблемы на вашей стороне. Либо ваш токен тоже умер или проблемы с подключением к серверу.

**Comment by Matrix3007** [comment]
Я правильно понимаю, что файл должен выглядеть так, как на скрине? Всё равно не получается. Токен не умер, так как я его не использовал ни разу, он мне выдался сразу при регистрации, а к серверу я подключаюсь без проблем.
![image](https://user-images.githubusercontent.com/60185573/88459355-77019080-ce9d-11ea-8fc5-e88dc05c2aa4.png)
![image](https://user-images.githubusercontent.com/60185573/88459361-8680d980-ce9d-11ea-89ea-65eb3076491c.png)

**Comment by kovinevmv** [comment]
@Matrix3007 проблема в Вашем токене, он невалидный. Я вставил свой токен, который получил сегодня (29.07.2020), запрос прошел, пользователь найден.
