### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by Piskuliki0723** [kovinevmv/getcontact#18]
python3 ./src/main.py -p +79291045342  Traceback (most recent call last):       File "./src/main.py", line 19, in <module>                                      getcontact.print_information_by_phone(phone)                                File "/data/data/com.termux/files/home/getcontact/src/getcontact/getcontact.py", line 79, in print_information_by_phone                                       data = self.get_information_by_phone(phone)                                 File "/data/data/com.termux/files/home/getcontact/src/getcontact/getcontact.py", line 71, in get_information_by_phone                                         result_name = self.get_name_by_phone(phone)                                 File "/data/data/com.termux/files/home/getcontact/src/getcontact/getcontact.py", line 16, in get_name_by_phone         response = self.requester.get_phone_name(phoneNumber)                       File "/data/data/com.termux/files/home/getcontact/src/getcontact/requester.py", line 117, in get_phone_name            return self.send_req_to_the_server(self.base_url + self.base_uri_api + method, self.request_data)                  File "/data/data/com.termux/files/home/getcontact/src/getcontact/requester.py", line 91, in send_req_to_the_server     is_ok, response = self.send_request_encrypted(url, payload)                 File "/data/data/com.termux/files/home/getcontact/src/getcontact/requester.py", line 56, in send_request_encrypted     return self._send_post(url, json.dumps({"data": self.cipher.encrypt_AES_b64(data)}))                               File "/data/data/com.termux/files/home/getcontact/src/getcontact/requester.py", line 52, in _send_post                 return self._parse_response(response)                                       File "/data/data/com.termux/files/home/getcontact/src/getcontact/requester.py", line 68, in _parse_response            response = response.json()['data'] KeyError: 'data'

**Comment by ekifox** [comment]
`➜  getcontact git:(master) docker run -t getcontact -p +79291045342
Traceback (most recent call last):
  File "./src/main.py", line 19, in <module>
    getcontact.print_information_by_phone(phone)
  File "/src/getcontact/getcontact.py", line 79, in print_information_by_phone
    data = self.get_information_by_phone(phone)
  File "/src/getcontact/getcontact.py", line 71, in get_information_by_phone
    result_name = self.get_name_by_phone(phone)
  File "/src/getcontact/getcontact.py", line 16, in get_name_by_phone
    response = self.requester.get_phone_name(phoneNumber)
  File "/src/getcontact/requester.py", line 117, in get_phone_name
    return self.send_req_to_the_server(self.base_url + self.base_uri_api + method, self.request_data)
  File "/src/getcontact/requester.py", line 91, in send_req_to_the_server
    is_ok, response = self.send_request_encrypted(url, payload)
  File "/src/getcontact/requester.py", line 56, in send_request_encrypted
    return self._send_post(url, json.dumps({"data": self.cipher.encrypt_AES_b64(data)}))
  File "/src/getcontact/requester.py", line 52, in _send_post
    return self._parse_response(response)
  File "/src/getcontact/requester.py", line 68, in _parse_response
    response = response.json()['data']
KeyError: 'data'
➜  getcontact git:(master)`

**Comment by kovinevmv** [comment]
@ekifox, @Piskuliki0723  please run script in [debug mode](https://github.com/kovinevmv/getcontact#debug-mode) and send me log. Maybe your are using incorrect tokens, or tokens which are dead.
