### ISSUE TITLE
Вопрос.

### ISSUE THREAD

**Issue by Arbuzzzzzz** [kovinevmv/getcontact#19]
Спасибо за рабочий код. Хотел спросить, не скажете какими программными инструментами вы пользовались для изучения API getContact? Заранее большое спасибо.

**Comment by kovinevmv** [comment]
Reverse apk: http://www.javadecompilers.com/apk
Reverse anything: https://www.hex-rays.com/products/ida/
Intercept Android traffic: https://portswigger.net/burp

**Comment by Arbuzzzzzz** [comment]
Супер. Спасибо. Трафик от приложения анализировали в Burp?

**Comment by kovinevmv** [comment]
Да

**Comment by Arbuzzzzzz** [comment]
Еще раз огромное спасибо. Ветку можно закрывать.
