### ISSUE TITLE
requester.py:22

### ISSUE THREAD

**Issue by MrKira34** [kovinevmv/getcontact#6]
Максим, подскажите. А реально ли генерировать эти токены "AES key", "token", "exp" самому, не вытаскивая их каждый раз из приложения после прохождения регистрации на новый номер.
Изучали вот эту статью: [https://github.com/chipik/ya_perezvonu/blob/master/rev/README.md](url)
Она была написана год назад, но тут человек показал как это делать. Возможно ли это сейчас?
Так же в вашем коде requester.py:22 видим, что есть метод register, но он никак нигде не используется.

**Comment by MrKira34** [comment]
Разобрались, что token приходит чистым из register, приватный ключ нужен для вычисления AES ключа, а вот как приватный сделать.

**Comment by MrKira34** [comment]
А, так у вас и метод создания AES описан, но нигде не используется.. То есть если в yaml приват ключ удалить, все равно все так же работать будет.

**Comment by kovinevmv** [comment]
Я видел [репозиторий](https://github.com/chipik/ya_perezvonu) и изучал его, но в подробности генерации токенов, ключей не вникал. 
Возможно можно сделать авторизацию/регистрацию через код, но у меня пока нет на это времени. 
Скорее всего PRIVATE_KEY не нужен.

**Comment by kovinevmv** [comment]
PRIVATE_KEY гененрируется пользователем, рассчитывается peerKey по формуле `7 **  PRIVATE_KEY mod 90071992548` и передается серверу, в ответ получаем serverKey, на основе которого по формуле `serverKey ** PRIVATE_KEY mod 90071992548` получается AES_KEY. 
Это обычный Диффи-Хеллман
