### ISSUE TITLE
Не работает поиск

### ISSUE THREAD

**Issue by Zzayj** [kovinevmv/getcontact#66]
root@fro:~/getcontact/src# python3 main.py -p +79503343722
Traceback (most recent call last):
  File "main.py", line 3, in <module>
    from getcontact.getcontact import GetContactAPI
  File "/root/getcontact/src/getcontact/getcontact.py", line 25
    user_name = f'{parse_none(name)} {parse_none(surname)}'

**Comment by kovinevmv** [comment]
Нужно исправлять работу скрипта и заново изучать API GetContact, на что у меня нет времени, так что ближайшее время фиксов не будет

**Comment by kovinevmv** [comment]
Необходимо поставить python3.7
