### ISSUE TITLE
How to bypass captcha??

### ISSUE THREAD

**Issue by MrG3P5** [kovinevmv/getcontact#68]
before I run it works, but when it's 3x requests it outputs input like this...

Captcha is detected. 
Captcha is detected.
Captcha is detected. 
Captcha is detected.
Captcha is detected. 
Captcha is detected.

so how we can run again?

**Comment by yogipw** [comment]
bang mrgrpe

**Comment by kovinevmv** [comment]
https://github.com/kovinevmv/getcontact/issues/48#issuecomment-1059809671

**Comment by yagamicell** [comment]
create X- req signature not working.. because for now i see in request header use X-Req-Timestamp: with miliseconds time 13 digits unixtime not 10 digits
