### ISSUE TITLE
ModuleNotFoundError: No module named 'yaml'

### ISSUE THREAD

**Issue by dcode-denpa** [kovinevmv/getcontact#73]
$ pip install yaml  
ERROR: Could not find a version that satisfies the requirement yaml (from versions: none)
ERROR: No matching distribution found for yaml

**Comment by kovinevmv** [comment]
The response with 403 in any case contains a body with information about the error. You need to know the keys to decrypt this message from the server and see what the error is.

Most likely, you have an invalid token if you take it from the repository.

**Comment by kovinevmv** [comment]
HMAC key must be valid, i dont think that its not changed: https://github.com/kovinevmv/getcontact/blob/master/src/getcontact/config.py#L34

**Comment by budiprihhastomo** [comment]
Can you explain to me, how to get this HMAC when reverse this apk ?

**Comment by budiprihhastomo** [comment]
I don't think HMAC exists when intercepting the network, but in the app's source code.

Interested! 😂

**Comment by kovinevmv** [comment]
I did not mean to intercept traffic, I mead to intercept the values ​​of the variables of the executable code

**Comment by budiprihhastomo** [comment]
It's okay, thank you for your response.

**Comment by kovinevmv** [comment]
Glad to help you
