### ISSUE TITLE
what is your decompiler?

### ISSUE THREAD

**Issue by datacoderid** [kovinevmv/getcontact#74]
hi kovin,

amaze how you can find the encryption key. i tried to decompile using jadx, but still very hard to read the code.
May i know what is your decompiler tools?

**Comment by kovinevmv** [comment]
Hi, encryption key is not saved in source code. I decompiled with JADX. U should intercept it in runtime with frida

**Comment by datacoderid** [comment]
Hi,

Oops, I mean encryption algorithm like EBC. Thanks for sharing about Frida, will try to explore
