### ISSUE TITLE
Register a getcontact account in the emulator

### ISSUE THREAD

**Issue by Nux-xader** [kovinevmv/getcontact#75]
how do I register a get contact account in the emulator, I've tried it but getcontact detects incoming calls is there an alternative so I can register an account via the emulator, without using verification via whatsapp

**Comment by kovinevmv** [comment]
Can u try to install Android 6.0 Emulator? Genymotion can emulate incoming calls. U have to pass verification stesp in getcontact, without auth u cannot use it and intercept credential.s

**Comment by Nux-xader** [comment]
Is it possible to reverse engineer and then change the path of the GetContactSettingsPref.xml file outside the root directory, for example sdcard, so you can get the key without needing root access?

**Comment by kovinevmv** [comment]
No way, it is strongly restricted by Android OS to change sandbox path of app

**Comment by Nux-xader** [comment]
do you think there is another alternative so that I can still get the key without root access

**Comment by kovinevmv** [comment]
It's better to install rooted emulator or root ur physical device. I don't know other approaches.

**Comment by Navitas28** [comment]
@Nux-xader were you able to find the file in the rooted emulated device ?

**Comment by Nux-xader** [comment]
> were you able to find the file in the rooted emulated device ?

I haven't tried it because I was blocked when I wanted to register my account via the emulator

**Comment by Navitas28** [comment]
@kovinevmv Could you please suggest me what else I can do , For my setup I am unable to find the file, firstly in `genymotion` play store `getcontact` app is not available, downloaded the app via third-party vendors like `apkpure` but unable to locate the files at the suggested location

**Comment by kovinevmv** [comment]
Download APK file on PC from website using ur browser. Find it in explorer (find the folder). Run emulator. Then drag&drop file from folder of PC to emulator window. APK will be installed.

**Comment by Navitas28** [comment]
Thanks for the response, that I was able to do it but still in file explorer not able to find the file, the `app.source.getcontact` folder is empty

**Comment by kovinevmv** [comment]
Default android explorer doesn't have root right. Install something like "Root explorer" app
