### ISSUE TITLE
Just curious!

### ISSUE THREAD

**Issue by aunicorn111** [kovinevmv/getcontact#77]
Hello! I was wondering if yout api still works? Last update from 2021 said that it does not, but I was wondering maybe it has been fixed since then?? ^ ^'' 
I'm asking because no matter what phone number I put in, it says user not found and I want to know if it's me doing something wrong or the code.
Thank you for your answer! :smiley:

**Comment by aunicorn111** [comment]
Also, I saw some kind of "tokens" mentioned in readme. How do I get those?? :eyes:

**Comment by aunicorn111** [comment]
Почему-то не сразу дошло что тут русскоговорящие, несмотря на то что в readme русский язык ха-ха :blush: 

Так вот, с токеном вроде поняла, его надо брать где-то из памяти телефона/эмулятора с правами администратора. Препдположу что как только будут заменены эти данные код снова начнёт работать :relaxed:

**Comment by kovinevmv** [comment]
Приветствую. 
Да, код актуальный и рабочий. Необходимо использовать свою сессию для использования скрипта. Для извлечения токенов нужен Android с ROOT правами

**Comment by aunicorn111** [comment]
> Приветствую. Да, код актуальный и рабочий. Необходимо использовать свою сессию для использования скрипта. Для извлечения токенов нужен Android с ROOT правами

Я конечно очень обнаглею, но всё же спрошу. А как именнно извлекаются токены? Ну то есть... Куда за ними лезть? :eyes: Они где-то в памяти телефона в открытую лежат или нужны доп инструменты??

**Comment by kovinevmv** [comment]
Нужен Android с ROOT, устанавливаешь GetContact, авторизуешься. 
Далее нужен проводник в файловую систему телефона, можно через adb С ПК, можно через приложение на телефон ROOT Explorer. 
А дальше искать нужные строчки в `/data/data/app.source.getcontact/shared_prefs/GetContactSettingsPref.xml`
