### ISSUE TITLE
Why Not GetContact Web

### ISSUE THREAD

**Issue by sooluh** [kovinevmv/getcontact#79]
Just suggesting and wondering, why not utilize GetContact Web at the moment?

**Comment by kovinevmv** [comment]
Hello @sooluh.

Yeah, Getcontact Web API provides the same information about user as a mobile application.

But u have to solve ReCaptcha per every search request to receive information about phone number. It's require external service integration to solve this captcha for money. In mobile app with not plain REST API protocol u can do it free using only ur authorization limits. 

See picture below
![Screenshot from 2024-02-25 13-13-53](https://github.com/kovinevmv/getcontact/assets/21666349/5f65ac0c-8c16-46d2-bebb-68329e687487)

**Comment by sooluh** [comment]
ah I see, previously I thought it's enough to just go to `/list-tag` without having to solve the captcha on `/search`, turns out `/list-tag` needs to go through `/search` first. I'll close this issue. Thanks!
