### ISSUE TITLE
Число запросов

### ISSUE THREAD

**Issue by frech87** [kovinevmv/getcontact#8]
Здравствуйте. Отличная работа. Интересует число запросов. Так как в самом приложении ограничено число запросов. Тут у вас вижу Remain Count, если его всегда держать в ноль, можно ли сделать безлимитный поиск? Так создать брутфорс для номеров

**Comment by kovinevmv** [comment]
Нет, число запросов на аккаунт хранится на сервере и возвращается в переменной Remain Count. Если число вернулось равным 0, то аккаунту не доступен поиск по номеру и придется ждать следующего месяца до обнуления запросов и вновь возвращения до 200. 
В yaml файле хранится именно возвращенный результат с сервера для того, чтобы определять доступен ли поиск или нет. Изменение значений Remain Count никак не влияет на доступное количество запросов для аккаунта. Только если поставите 0, то аккаунт не будет использоваться.

**Comment by frech87** [comment]
Спасибо за ответ. Был один телеграм бот, который обрабатывал много запросов, который превышал лимит. Интересно, как он обходил это

**Comment by kovinevmv** [comment]
Возможно много аккаунтов, много токенов. Я не могу сказать точно, лучше уточните у автора бота.

**Comment by frech87** [comment]
спасибо

**Comment by Matrix3007** [comment]
> Спасибо за ответ. Был один телеграм бот, который обрабатывал много запросов, который превышал лимит. Интересно, как он обходил это

Именно, что много токенов использовали. А как их получали - непонятно.

**Comment by kovinevmv** [comment]
> > Спасибо за ответ. Был один телеграм бот, который обрабатывал много запросов, который превышал лимит. Интересно, как он обходил это
> 
> Именно, что много токенов использовали. А как их получали - непонятно.

Добавили автоматическую регистрацию, указали набор номеров или динамически подгружали с какого-нибудь онлайн-сервиса виртуальных номеров, callback на ввод кода из SMS и сохранили токены. 

Регистрация сейчас идет по [протоколу Диффи Хеллмана](https://en.wikipedia.org/wiki/Diffie%E2%80%93Hellman_key_exchange).

**Comment by Matrix3007** [comment]
> > > Спасибо за ответ. Был один телеграм бот, который обрабатывал много запросов, который превышал лимит. Интересно, как он обходил это
> > 
> > 
> > Именно, что много токенов использовали. А как их получали - непонятно.
> 
> @Matrix3007
> Добавили автоматическую регистрацию, указали набор номеров или динамически подгружали с какого-нибудь онлайн-сервиса виртуальных номеров, callback на ввод кода из SMS и сохранили токены.
> 
> Регистрация сейчас идет по [протоколу Диффи Хеллмана](https://en.wikipedia.org/wiki/Diffie%E2%80%93Hellman_key_exchange).

Но разве количества токенов, которое можно получить таким способом, хватит, чтобы спарсить такую огромную базу? Там ведь десятки миллионов номеров.

**Comment by kovinevmv** [comment]
@Matrix3007 я не знаю, у меня нет такой цели. Если у Вас есть другое предположение, то можете высказать.

**Comment by Matrix3007** [comment]
> @Matrix3007 я не знаю, у меня нет такой цели. Если у Вас есть другое предположение, то можете высказать.

Можно ли регистрироваться множество раз с одним и тем же номером, каждый раз получая разные токены?

**Comment by kovinevmv** [comment]
@Matrix3007 я не знаю, можете сами проверить
