### ISSUE TITLE
Authentication failed : 'errorCode': '403003

### ISSUE THREAD

**Issue by FerlanGhaly** [kovinevmv/getcontact#80]
I Got My own token and key from a fresh installation of getcontact app on a rooted device
No Matter What Phone Number i Search For i get the same error 
Authentication Failed & Error Code 403003

Thanks in Advance

**Comment by kovinevmv** [comment]
Possibly, ur token was banned by Getcontact anti fraud system

**Comment by FerlanGhaly** [comment]
the token works fine on the application and retrieves the result successfully with the same token

**Comment by kovinevmv** [comment]
Maybe banned IP address, i cant help u to debug it.
