### ISSUE TITLE
key error

### ISSUE THREAD

**Issue by altysheff** [kovinevmv/getcontact#9]
Error code: 403021
Error message: You have reached maximum query limit. Thank you for using Getcontact.
But if I try to delete "+", I get:
Error code: 403021
Error message: You have reached maximum query limit. Thank you for using Getcontact.
AND
Phone: XXXXXXXXXXX (i hide my phone)
User: Not Found
Tag list:
         Arthur
         Arthuuur

**Comment by kovinevmv** [comment]
This means that the tokens in the repository have died and are not valid. Check the server’s response on "remainCount" value. Most likely the value is 0. 
Use your tokens for requests.
